name: PR Checklist

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  contents: read

jobs:
  check-pr-template:
    name: Check PR template
    uses: beeware/.github/.github/workflows/pr-checklist.yml@d36f8fe66673484b598317adaab0433518b122f6
