name: CI
on:
  pull_request:
  push:
    branches:
      - main
  workflow_call:

# Cancel active CI runs for a PR before starting another run
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  FORCE_COLOR: "1"

jobs:
  pre-commit:
    name: Pre-commit checks
    uses: beeware/.github/.github/workflows/pre-commit-run.yml@main
    with:
      pre-commit-source: pre-commit

  verify-apps:
    name: Build apps
    needs: pre-commit
    uses: beeware/.github/.github/workflows/app-build-verify.yml@main
    with:
      python-version: ${{ matrix.python-version }}
      runner-os: ${{ matrix.runs-on }}
      framework: ${{ matrix.framework }}
      target-platform: Windows
      target-format: app
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13", "3.14" ]
        framework: [ "toga", "pyside6", "pygame", "console" ]
        runs-on: ["windows-latest", "windows-11-arm"]
        exclude:
          # Github Actions doesn't provide Windows/ARM64 builds for Python 3.10
          - python-version: "3.10"
            runs-on: "windows-11-arm"
          # Pygame hasn't published 3.14 wheels.
          - python-version: "3.14"
            framework: pygame
          # Pygame hasn't published any Windows/ARM64 wheels.
          - framework: pygame
            runs-on: windows-11-arm
          # Toga is waiting on a release of Python.net for 3.14
          - python-version: "3.14"
            framework: toga
          # Toga tests won't run on Windows/ARM64 until
          # https://github.com/actions/partner-runner-images/issues/174 is resolved
          - framework: "toga"
            runs-on: windows-11-arm
