name: CI
on:
  pull_request:
  push:
    branches:
      - main
  workflow_call:

defaults:
  run:
    shell: bash # https://github.com/beeware/briefcase/pull/912

jobs:
  verify-apps:
    name: Build apps
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.8", "3.9", "3.10", "3.11"]
        framework: ["toga", "pyside2", "pyside6", "ppb"]
        include:
          - platform: windows-latest
            briefcase-data-dir: ~\AppData\Local\BeeWare\briefcase\Cache
            pip-cache-dir: ~\AppData\Local\pip\Cache
            docker-cache-dir: C:\ProgramData\DockerDesktop
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Cache Briefcase tools
        uses: actions/cache@v3.0.11
        with:
          key: briefcase-${{ matrix.platform }}-${{ matrix.python_version }}
          path: |
            ~/.cookiecutters
            ${{ matrix.briefcase-data-dir }}
            ${{ matrix.pip-cache-dir }}
            ${{ matrix.docker-cache-dir }}
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install dependencies
        run: |
          python -m pip install briefcase
      - name: Build App
        run: |
          cd tests/apps/verify-${{ matrix.framework }}
          briefcase create
          briefcase build
          briefcase package --adhoc-sign
